spring:
    application:
        name: admin-back
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
server:
    port: 8762
    tomcat:
      uri-encoding: utf-8